import { defineConfig } from "@/lib/config";

// Private clone configuration - generated by setup script
const useCloneBranding = true;

export default defineConfig({
  // Branding - your organization's identity
  branding: {
    name: "Quoreka",
    logo: "/quoreka.svg",
    logoDark: "/quoreka.svg",
    favicon: "/logo.svg",
    description: "Collect, organize, and share AI prompts",
  },

  // Theme - design system configuration
  theme: {
    radius: "sm",
    variant: "default",
    density: "comfortable",
    colors: {
      primary: "#6366f1",
    },
  },

  // Authentication plugins
  auth: {
    providers: ["credentials"],
    allowRegistration: true,
  },

  // Internationalization
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },

  // Features
  features: {
    privatePrompts: true,
    changeRequests: true,
    categories: true,
    tags: true,
    comments: true,
    aiSearch: false,
    aiGeneration: false,
    mcp: false,
    sharePrompts: false,
  },

  // Homepage customization (clone branding mode)
  homepage: {
    useCloneBranding,
    achievements: {
      enabled: false, // Disabled for private clones
    },
    sponsors: {
      enabled: !useCloneBranding,
      items: [
        // Add sponsors here
        { name: "Clemta", logo: '/sponsors/clemta.webp', url: "https://clemta.com/?utm_source=prompts.chat" },
        { name: "Wiro.ai", className: 'py-1', darkLogo: '/sponsors/wiro.png', logo: '/sponsors/wiro.png', url: "https://wiro.ai/?utm_source=prompts.chat" },
        { name: "Cognition", logo: "/sponsors/cognition.svg", url: "https://wind.surf/prompts-chat" },
        { name: "CodeRabbit", className: 'py-1', logo: '/sponsors/coderabbit.svg', darkLogo: '/sponsors/coderabbit-dark.svg', url: "https://coderabbit.link/fatih" },
        { name: "Sentry", className: 'py-1', logo: '/sponsors/sentry.svg', darkLogo: '/sponsors/sentry-dark.svg', url: "https://sentry.io/?utm_source=prompts.chat" },
        { name: "MitteAI", logo: '/sponsors/mitte.svg', darkLogo: '/sponsors/mitte-dark.svg', url: "https://mitte.ai/?utm_source=prompts.chat" },
        { name: "eachlabs", className: 'py-[6px]', logo: '/sponsors/eachlabs.png', darkLogo: '/sponsors/eachlabs-dark.png', url: "https://www.eachlabs.ai/?utm_source=promptschat&utm_medium=referral" },
        { name: "warp.dev", className: 'py-2', logo: '/sponsors/warp.svg', url: "https://warp.dev/?utm_source=prompts.chat" },
      ],
    },
  },
});
